/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import SistemaAlarmaBloqueo.Bloqueo;
import SistemaControlCinturones.ControlCinturon;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

    
/**
 *
 * @author alexr
 */
public class CinturonesYPuertasIFrm extends javax.swing.JInternalFrame {
    
    private String usuarioSeleccionado;

    private ControlCinturon cinturonChofer;
    
    private ControlCinturon cinturonAcompanante;
    
    private Bloqueo bloqueoChofer;
    
     private Bloqueo bloqueoAcompanante;
    
    ImageIcon cinturonC = new ImageIcon(getClass().getResource("/Images/cinturonC.png"));
    ImageIcon cinturonA = new ImageIcon(getClass().getResource("/Images/cinturonA.png"));
    ImageIcon carro = new ImageIcon(getClass().getResource("/Images/Carro.png"));
    ImageIcon puertaP = new ImageIcon(getClass().getResource("/Images/PuertaPiloto.png"));
    ImageIcon puertaC = new ImageIcon(getClass().getResource("/Images/PuertaCopiloto.png"));
    ImageIcon Candado = new ImageIcon(getClass().getResource("/Images/candado.png"));
    /**
     * Creates new form CinturonesIFrm
     */
    public CinturonesYPuertasIFrm() {
        initComponents();
        this.cinturonAcompanante = new ControlCinturon();
        this.cinturonChofer = new ControlCinturon();
        this.usuarioSeleccionado = "chofer";
        this.bloqueoChofer = new Bloqueo();
        this.bloqueoAcompanante = new Bloqueo();
        lblPuertaConductor.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (lblPuertaConductor.getWidth() > 0 && lblPuertaConductor.getHeight() > 0) {
                    Image imagenEscaladaConductor = carro.getImage().getScaledInstance(lblPuertaConductor.getWidth(), lblPuertaConductor.getHeight(), Image.SCALE_SMOOTH);
                    lblPuertaConductor.setIcon(new ImageIcon(imagenEscaladaConductor));
                    lblPuertaConductor.removeComponentListener(this);
                }
            }
        });
        lblPuertaAcompanante.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                if (lblPuertaAcompanante.getWidth() > 0 && lblPuertaAcompanante.getHeight() > 0) {
                    Image imagenEscaladaAcompanante = carro.getImage().getScaledInstance(lblPuertaAcompanante.getWidth(), lblPuertaAcompanante.getHeight(), Image.SCALE_SMOOTH);
                    lblPuertaAcompanante.setIcon(new ImageIcon(imagenEscaladaAcompanante));
                    lblPuertaAcompanante.removeComponentListener(this);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblControlCinturones = new javax.swing.JLabel();
        lblConductor = new javax.swing.JLabel();
        lblPasajero = new javax.swing.JLabel();
        lblCinturonPasajero = new javax.swing.JLabel();
        lblCinturonConductor = new javax.swing.JLabel();
        btnColocar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        lblControlPuertas = new javax.swing.JLabel();
        btnConductor = new javax.swing.JButton();
        btnPasajero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPuertaConductor = new javax.swing.JLabel();
        lblPuertaAcompanante = new javax.swing.JLabel();
        btnAbrirPuerta = new javax.swing.JButton();
        btnBloquearPuerta = new javax.swing.JButton();
        btnCerrarPuerta = new javax.swing.JButton();
        btnDesbloquearPuerta = new javax.swing.JButton();
        lblCandadoConductor = new javax.swing.JLabel();
        lblCandadoPasajero = new javax.swing.JLabel();

        setClosable(true);

        lblControlCinturones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblControlCinturones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControlCinturones.setText("Control de cinturones");

        lblConductor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConductor.setText("Cinturon Conductor");

        lblPasajero.setText("Cinturon Pasajero");

        lblCinturonPasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cinturonA.png"))); // NOI18N

        lblCinturonConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cinturonA.png"))); // NOI18N

        btnColocar.setText("Colocar");
        btnColocar.setToolTipText("");
        btnColocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColocarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lblControlPuertas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblControlPuertas.setText("Control de puertas");

        btnConductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/persona1.png"))); // NOI18N
        btnConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductorActionPerformed(evt);
            }
        });

        btnPasajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/persona1.png"))); // NOI18N
        btnPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasajeroActionPerformed(evt);
            }
        });

        jLabel1.setText("Conductor");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pasajero");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Puerta Conductor");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Puerta Pasajero");

        btnAbrirPuerta.setText("Abrir");
        btnAbrirPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPuertaActionPerformed(evt);
            }
        });

        btnBloquearPuerta.setText("Bloquear");
        btnBloquearPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearPuertaActionPerformed(evt);
            }
        });

        btnCerrarPuerta.setText("Cerrar");
        btnCerrarPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarPuertaActionPerformed(evt);
            }
        });

        btnDesbloquearPuerta.setText("Desbloquear");
        btnDesbloquearPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearPuertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblControlCinturones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblControlPuertas)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblConductor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblPasajero)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCandadoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCandadoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCinturonConductor)
                    .addComponent(lblCinturonPasajero)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnColocar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPuertaAcompanante, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAbrirPuerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBloquearPuerta, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPuertaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCerrarPuerta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDesbloquearPuerta, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(79, 79, 79)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblControlCinturones)
                    .addComponent(lblControlPuertas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addComponent(lblCandadoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblCandadoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPuertaAcompanante, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrarPuerta)
                            .addComponent(btnAbrirPuerta))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnColocar)
                                    .addComponent(btnQuitar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBloquearPuerta)
                                    .addComponent(btnDesbloquearPuerta))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCinturonConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblPasajero)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPuertaConductor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addComponent(lblCinturonPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColocarActionPerformed
        if(usuarioSeleccionado.equals("chofer") && !cinturonChofer.isColocado()){
            lblCinturonConductor.setIcon(cinturonC);
            cinturonChofer.colocar();
        } 
        if(usuarioSeleccionado.equals("acompanante") && !cinturonAcompanante.isColocado()){
            lblCinturonPasajero.setIcon(cinturonC);
            cinturonAcompanante.colocar();
        }
    }//GEN-LAST:event_btnColocarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
       if(usuarioSeleccionado.equals("chofer") && cinturonChofer.isColocado()){
            lblCinturonConductor.setIcon(cinturonA);
            cinturonChofer.quitar();
        } 
        if(usuarioSeleccionado.equals("acompanante") && cinturonAcompanante.isColocado()){
            lblCinturonPasajero.setIcon(cinturonA);
            cinturonAcompanante.quitar();
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajeroActionPerformed
        usuarioSeleccionado = "acompanante";
    }//GEN-LAST:event_btnPasajeroActionPerformed

    private void btnConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductorActionPerformed
        usuarioSeleccionado = "chofer";
    }//GEN-LAST:event_btnConductorActionPerformed

    private void btnAbrirPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPuertaActionPerformed
        if (usuarioSeleccionado.equals("chofer")) {
            if (!bloqueoChofer.isBloqueado()) {
                Image imagenEscalada = puertaP.getImage().getScaledInstance(
                        lblPuertaConductor.getWidth(), lblPuertaConductor.getHeight(), Image.SCALE_SMOOTH);
                lblPuertaConductor.setIcon(new ImageIcon(imagenEscalada));
            } else {
                JOptionPane.showMessageDialog(null, "El chofer está bloqueado. No se puede abrir la puerta.");
            }
        }

        if (usuarioSeleccionado.equals("acompanante")) {
            if (!bloqueoAcompanante.isBloqueado()) {
                Image imagenEscalada = puertaP.getImage().getScaledInstance(
                        lblPuertaAcompanante.getWidth(), lblPuertaAcompanante.getHeight(), Image.SCALE_SMOOTH);
                lblPuertaAcompanante.setIcon(new ImageIcon(imagenEscalada));
            } else {
                JOptionPane.showMessageDialog(null, "El acompañante está bloqueado. No se puede abrir la puerta.");
            }
        }
    }//GEN-LAST:event_btnAbrirPuertaActionPerformed

    private void btnDesbloquearPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearPuertaActionPerformed
         if (usuarioSeleccionado.equals("chofer")) {
             bloqueoChofer.desbloquear();
             lblCandadoConductor.setIcon(null);
         }
         if (usuarioSeleccionado.equals("acompanante")) {
             bloqueoAcompanante.desbloquear();
             lblCandadoPasajero.setIcon(null);
         }
    }//GEN-LAST:event_btnDesbloquearPuertaActionPerformed

    private void btnCerrarPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarPuertaActionPerformed
        if (usuarioSeleccionado.equals("chofer")) {
            Image imagenEscalada = carro.getImage().getScaledInstance(lblPuertaConductor.getWidth(), lblPuertaConductor.getHeight(), Image.SCALE_SMOOTH);
            lblPuertaConductor.setIcon(new ImageIcon(imagenEscalada));
        }
        if (usuarioSeleccionado.equals("acompanante")) {
            Image imagenEscalada = carro.getImage().getScaledInstance(lblPuertaAcompanante.getWidth(), lblPuertaAcompanante.getHeight(), Image.SCALE_SMOOTH);
            lblPuertaAcompanante.setIcon(new ImageIcon(imagenEscalada));
        } 
    }//GEN-LAST:event_btnCerrarPuertaActionPerformed

    private void btnBloquearPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearPuertaActionPerformed
           if (usuarioSeleccionado.equals("chofer")) {
            bloqueoChofer.bloquear();
            Image imagenEscalada = Candado.getImage().getScaledInstance(lblCandadoConductor.getWidth(), lblCandadoConductor.getHeight(), Image.SCALE_SMOOTH);
            lblCandadoPasajero.setIcon(new ImageIcon(imagenEscalada));
        }
        if (usuarioSeleccionado.equals("acompanante")) {
            bloqueoAcompanante.bloquear();
            Image imagenEscalada = Candado.getImage().getScaledInstance(lblCandadoPasajero.getWidth(), lblCandadoPasajero.getHeight(), Image.SCALE_SMOOTH);
            lblCandadoConductor.setIcon(new ImageIcon(imagenEscalada));
        }
    }//GEN-LAST:event_btnBloquearPuertaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPuerta;
    private javax.swing.JButton btnBloquearPuerta;
    private javax.swing.JButton btnCerrarPuerta;
    private javax.swing.JButton btnColocar;
    private javax.swing.JButton btnConductor;
    private javax.swing.JButton btnDesbloquearPuerta;
    private javax.swing.JButton btnPasajero;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCandadoConductor;
    private javax.swing.JLabel lblCandadoPasajero;
    private javax.swing.JLabel lblCinturonConductor;
    private javax.swing.JLabel lblCinturonPasajero;
    private javax.swing.JLabel lblConductor;
    private javax.swing.JLabel lblControlCinturones;
    private javax.swing.JLabel lblControlPuertas;
    private javax.swing.JLabel lblPasajero;
    private javax.swing.JLabel lblPuertaAcompanante;
    private javax.swing.JLabel lblPuertaConductor;
    // End of variables declaration//GEN-END:variables
}
