/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Motor.Motor;
import java.awt.Color;
import javax.swing.Timer;

/**
 *
 * @author alexr
 */
public class MotorIFrm extends javax.swing.JInternalFrame {

    private Motor motor;
    private Timer timer;
    /**
     * Creates new form MotorIFrm
     */
    public MotorIFrm() {
        initComponents();
        motor = new Motor();
        lblKilometraje.setText("Kilometraje: " + String.format("%.2f", motor.getKilometraje()) + " km");
        lblVelocidad.setText("Velocidad: " + motor.getVelocidad() + " km/h");
        lblRPM.setText("RPM: " + motor.getRpm());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEncender = new javax.swing.JButton();
        lblMotor = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        lblRPM = new javax.swing.JLabel();
        lblKilometraje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboMarchas = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);

        btnEncender.setText("Encender");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        lblMotor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMotor.setForeground(new java.awt.Color(153, 0, 0));
        lblMotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotor.setText("Motor");

        lblVelocidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblVelocidad.setText("Velocidad");

        lblRPM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRPM.setText("RPM");

        lblKilometraje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKilometraje.setText("Kilometraje");

        jButton1.setText("Apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboMarchas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R", "N", "1", "2", "3" }));
        comboMarchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarchasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboMarchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEncender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(lblVelocidad)
                    .addComponent(lblRPM)
                    .addComponent(lblKilometraje))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMarchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncender)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVelocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKilometraje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        motor.encender();
        lblMotor.setForeground(Color.green);
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (motor.isEncendido()){
            motor.apagar();
            lblMotor.setForeground(Color.red);
            lblKilometraje.setText("Kilometraje: " + String.format("%.2f", motor.getKilometraje()) + " km");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboMarchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarchasActionPerformed
        
        String marcha = (String) comboMarchas.getSelectedItem();
    int velocidad = 0;
    switch (marcha) {
        case "N":
            velocidad = 0;
            break;
        case "1":
            velocidad = 20;
            break;
        case "2":
            velocidad = 40;
            break;
        case "3":
            velocidad = 60;
            break;
        case "R":
            velocidad = 10;
            break;
    }
        motor.setVelocidad(velocidad);
        lblVelocidad.setText("Velocidad: " + motor.getVelocidad() + " km/h");
        lblRPM.setText("RPM: " + motor.getRpm());
    }//GEN-LAST:event_comboMarchasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncender;
    private javax.swing.JComboBox<String> comboMarchas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblKilometraje;
    private javax.swing.JLabel lblMotor;
    private javax.swing.JLabel lblRPM;
    private javax.swing.JLabel lblVelocidad;
    // End of variables declaration//GEN-END:variables
}
