/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import java.io.File;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.Timer;
import sistParabrisas.EnumParabrisas;
import sistParabrisas.Parabrisas;

/**
 *
 * @author Braya
 */
public class ParabrisaslFrm extends javax.swing.JInternalFrame {
    
    private Parabrisas parabrisas = new Parabrisas() {};
    private Timer timer;
    private int frame = 1;



    /**
     * Creates new form ParabrisaslFrm
     */
    public ParabrisaslFrm() {
        initComponents();
        timer = new Timer(1000, e -> animarParabrisas());
        setImagenLabel(lblParabrisas, "src/images/parabrisas.png");
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
    }
    
    private void animarParabrisas() {
        String ruta = "src/images/Parabrisas" + frame + ".png";
        File archivo = new File(ruta);
        if (archivo.exists()) {
            setImagenLabel(lblParabrisas, archivo.getAbsolutePath());
        }
        frame++;
        if (frame > 3) {
            frame = 1;
        }
    }

    private void actualizarVelocidad(EnumParabrisas velocidad) {
        int delay;
        switch (velocidad) {
            case BAJO -> delay = 1200;
            case MEDIO -> delay = 800;
            case RAPIDO -> delay = 600;
            case APAGADO -> {
            timer.stop();
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/parabrisas1.png"));
            Image scaledImage = icon.getImage().getScaledInstance(lblParabrisas.getWidth(), lblParabrisas.getHeight(), Image.SCALE_SMOOTH);
            lblParabrisas.setIcon(new ImageIcon(scaledImage));
            return;
        }
        default -> delay = 1000;
    }
    timer.setDelay(delay);
    if (!timer.isRunning()) {
        timer.start();
    }
}
    
    private void setImagenLabel(JLabel lblParabrisas, String root) {
        ImageIcon image = new ImageIcon(root);
        int width = lblParabrisas.getWidth();
        int height = lblParabrisas.getHeight();
        if (width > 0 && height > 0) {
             Icon icon = new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
            lblParabrisas.setIcon(icon);
            this.repaint();
        } else {
          lblParabrisas.setIcon(image);
        }
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        btnEncender = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblVelocidadBaja = new javax.swing.JButton();
        lblVelocidadMedia = new javax.swing.JButton();
        lblVelocidadAlta = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblParabrisas = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Sistema de Limpiaparabrisas");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEstado.setText("Estado:");

        lblVelocidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVelocidad.setText("Velocidad:");

        btnEncender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEncender.setText("Encender");
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        lblVelocidadBaja.setText("Velocidad Baja");
        lblVelocidadBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVelocidadBajaActionPerformed(evt);
            }
        });

        lblVelocidadMedia.setText("Velocidad Media");
        lblVelocidadMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVelocidadMediaActionPerformed(evt);
            }
        });

        lblVelocidadAlta.setText("Velocidad Alta");
        lblVelocidadAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblVelocidadAltaActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado)
                                    .addComponent(lblVelocidad)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblVelocidadBaja)
                                .addGap(18, 18, 18)
                                .addComponent(lblVelocidadMedia)
                                .addGap(18, 18, 18)
                                .addComponent(lblVelocidadAlta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnEncender)
                                .addGap(74, 74, 74)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblParabrisas, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblEstado)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVelocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParabrisas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncender, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidadBaja)
                    .addComponent(lblVelocidadMedia)
                    .addComponent(lblVelocidadAlta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        if (parabrisas.isActividadParabrisas() == EnumParabrisas.APAGADO) {
            parabrisas.setActividadParabrisas(EnumParabrisas.BAJO);
            actualizarVelocidad(EnumParabrisas.BAJO);
            lblEstado.setText("Estado: Encendido");
            lblVelocidad.setText("Velocidad: " + parabrisas.isActividadParabrisas().getVelocidad());
        } else {
            lblEstado.setText("Parabrisas ya está encendido");
            lblVelocidad.setText("Velocidad: " + parabrisas.isActividadParabrisas().getVelocidad());
        }
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void lblVelocidadBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVelocidadBajaActionPerformed
       if (parabrisas.isActividadParabrisas() != EnumParabrisas.APAGADO) {
            parabrisas.setActividadParabrisas(EnumParabrisas.BAJO);
            actualizarVelocidad(EnumParabrisas.BAJO);
            lblEstado.setText("Estado: Encendido ");
            lblVelocidad.setText("Velocidad: " + parabrisas.isActividadParabrisas().getVelocidad());
        } else {
            lblEstado.setText("Primero debe encender el parabrisas.");
        }
    }//GEN-LAST:event_lblVelocidadBajaActionPerformed

    private void lblVelocidadMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVelocidadMediaActionPerformed
        if (parabrisas.isActividadParabrisas() != EnumParabrisas.APAGADO) {
            parabrisas.setActividadParabrisas(EnumParabrisas.MEDIO);
            actualizarVelocidad(EnumParabrisas.MEDIO);
            lblEstado.setText("Estado: Encendido");
            lblVelocidad.setText("Velocidad: " + parabrisas.isActividadParabrisas().getVelocidad());
        } else {
            lblEstado.setText("Primero debe encender el parabrisas.");
        }
    }//GEN-LAST:event_lblVelocidadMediaActionPerformed

    private void lblVelocidadAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblVelocidadAltaActionPerformed
        if (parabrisas.isActividadParabrisas() != EnumParabrisas.APAGADO) {
            parabrisas.setActividadParabrisas(EnumParabrisas.RAPIDO);
            actualizarVelocidad(EnumParabrisas.RAPIDO);
            lblEstado.setText("Estado: Encendido");
            lblVelocidad.setText("Velocidad: " +parabrisas.isActividadParabrisas().getVelocidad());
        } else {
        lblEstado.setText("Primero debe encender el parabrisas.");
        }
    }//GEN-LAST:event_lblVelocidadAltaActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed

        if (timer != null && timer.isRunning()) {
            timer.stop();
        }
        parabrisas.setActividadParabrisas(EnumParabrisas.APAGADO);  
        URL url = getClass().getClassLoader().getResource("images/Parabrisas1.png");
        if (url != null) {
            lblParabrisas.setIcon(new ImageIcon(url));
        }
        lblEstado.setText("Estado: Apagado");
        lblVelocidad.setText("Velocidad: " + parabrisas.isActividadParabrisas().getVelocidad());
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblParabrisas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JButton lblVelocidadAlta;
    private javax.swing.JButton lblVelocidadBaja;
    private javax.swing.JButton lblVelocidadMedia;
    // End of variables declaration//GEN-END:variables
}
